---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive

- name: build
  pull: default
  image: patwie/elm-app
  commands:
  - node -v
  - npm -v
  - elm-app build

- name: test
  pull: default
  image: node:11.13.0
  commands:
  - "echo \"none\""

- name: create_release
  pull: default
  image: patwie/tar
  commands:
    - tar -czvf infomark-ui.tar.gz build/ README.md

- name: publish_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - infomark-ui.tar.gz
    checksum:
      - md5
      - sha256
  when:
    event: tag

volumes:
- name: 2f746d702f6361636865
  host:
    path: /tmp/cache

---
kind: signature
hmac: 6865f3b7e98c6fd01d4ab1e13105e5758990a0d3ee8abacc391be61c7ce44b5b

...
